// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	OPENAI_API_KEY: string;
	GOOGLE_API_KEY: string;
	GOOGLE_CSE_ID: string;
	THEMOMATIC_KV: KVNamespace;
	CLIENT_KEY: string;
}
